#!/usr/bin/env bash
# Regenerate docs/BUILDLOG.md: every checklist task -> the commits that delivered it.
# Generated from git history only, so it cannot drift from what actually happened.
# Usage: scripts/buildlog.sh            (writes docs/BUILDLOG.md)
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"
out="docs/BUILDLOG.md"
checklist="docs/CHECKLIST.md"

# commit lines: <short-hash>\t<date>\t<task>\t<subject>, oldest first
commits="$(git log --reverse --no-merges --date=short \
  --format='%h%x09%ad%x09%(trailers:key=Task,valueonly,separator=%x2C)%x09%s' \
  | awk -F'\t' '$3 ~ /^T[0-9][0-9][0-9]$/')"

{
  echo "# Build log"
  echo
  echo "_Generated by \`scripts/buildlog.sh\` from \`git log\`. Do not edit by hand._"
  echo
  echo "Each row is a checklist task (\`docs/CHECKLIST.md\`) and the commits whose \`Task:\` trailer names it."
  echo "Stage 1 history (before the task-linked format) ends at \`c403373\`."
  echo
  total_commits="$(printf '%s\n' "$commits" | grep -c . || true)"
  tasks_with_commits="$(printf '%s\n' "$commits" | cut -f3 | sort -u | grep -c . || true)"
  echo "**Task-linked commits:** $total_commits · **Tasks with at least one commit:** $tasks_with_commits"
  echo
  echo "| Task | Priority | Done | Commits | First | Last | Title |"
  echo "|---|---|---|---|---|---|---|"
  printf '%s\n' "$commits" | cut -f3 | awk '!seen[$0]++' | sort | while read -r task; do
    [ -n "$task" ] || continue
    rows="$(printf '%s\n' "$commits" | awk -F'\t' -v t="$task" '$3==t')"
    hashes="$(printf '%s\n' "$rows" | cut -f1 | sed 's/.*/`&`/' | paste -sd ' ' -)"
    first="$(printf '%s\n' "$rows" | head -1 | cut -f2)"
    last="$(printf '%s\n' "$rows" | tail -1 | cut -f2)"
    line="$(grep -E "^- \[[ x]\] $task " "$checklist" || true)"
    prio="$(printf '%s' "$line" | grep -Eo '`P[012]`' | tr -d '`' || true)"
    done_mark="$(printf '%s' "$line" | grep -q '^- \[x\]' && echo '✔' || echo '…')"
    # Strip backticks before truncating so a cut can never leave an unclosed code span.
    title="$(printf '%s' "$line" | sed -E 's/^- \[[ x]\] T[0-9]{3} `P[012]` //; s/`//g; s/\|/\\|/g; s/</\&lt;/g; s/>/\&gt;/g')"
    [ "${#title}" -le 90 ] || title="${title:0:89}…"
    echo "| $task | ${prio:-?} | $done_mark | $hashes | $first | $last | $title |"
  done
} > "$out"

echo "wrote $out"
